### ISSUE TITLE
Recent version 13 release breaks Gnome 3.28.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by gene1wood** [injcristianrojas/UTCClock#10]
I got a notification of an update to UTCClock just now, I upgraded and Gnome Extensions reported `ERROR` I looked at the logs and they show

```
Error: Schema org.gnome.shell.extensions.utcclock could not be found for extension utcclock@injcristianrojas.github.com. Please check your installation.

Stack trace:
  getSettings@/home/gene/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/convenience.js:88:15
  UTCClockSettingsWidget<._init@/home/gene/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/prefs_window.js:20:26
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  UTCClockSettingsBox<._init@/home/gene/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/prefs.js:29:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/gene/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/prefs.js:36:17
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43
  ```

I uninstalled UTCClock and then went to re-install it and again got the same error.

Here's a recording of the installation process and error : https://youtu.be/bSfI3RZdAXg

Manually reverting to version `12` worked around the problem. I'm unsure where version `13` comes from since the head of `master` seems like it's [at version `12`](https://github.com/injcristianrojas/UTCClock/blob/58e0399a835206a14400df4cf4b8a54bf5a01c02/metadata.json#L9)

**Comment by lofidevops** [comment]
I get the same error message. I'm running GNOME Shell 3.30.2.

**Comment by brothersloth** [comment]
Hi. Same Error on Ubuntu 20.04 Gnome Shell 3.36.4

**Comment by lofidevops** [comment]
As a sidenote, I now get prompted to upgrade ~~every time I log in or wake from sleep~~ frequently. If the the underlying issue is incompatibility (rather than a bug) it would be preferable to remove the new version from shells that are not supported.

**Comment by injcristianrojas** [comment]
Fixed. Sorry for the inconvenience.
