### ISSUE TITLE
Install from Gnome Extensions site is missing the entire "schemas" directory!

### ISSUE THREAD

**Issue by FastThenLeft** [injcristianrojas/UTCClock#12]
Ubuntu 20.10 & Gnome 3.38.1:

I tested it both ways. If you install from https://extensions.gnome.org/extension/1183/utcclock/ the entire "schemas" directory is missing and you get an error.

If you install using these instructions:
cd ~/.local/share/gnome-shell/extensions/
git clone https://github.com/injcristianrojas/UTCClock.git utcclock@injcristianrojas.github.com
Then you get the "schemas" directory and everything runs fine!

Thanks for such a great app!

**Comment by jhpratt** [comment]
This must be what I was running across. I was thoroughly confused when switching back from my manually installed version caused an error. Same version for both here.

**Comment by injcristianrojas** [comment]
The schemas issue has been fixed and submitted to GNOME Extensions, but the approval process is taking too long.

**Comment by injcristianrojas** [comment]
Plugin has been updated.
