### ISSUE TITLE
Disable "showMenu" when clicking with left button

### ISSUE THREAD

**Issue by vicentebolea** [injcristianrojas/UTCClock#14]
The current behavior of the mouse click is cumbersome and straange. 

Normally in GNOME and its extensions you can only access the menu when you press the right button of the mouse or there is an drop-down drawers with a settings option.

I propose either:

- Fully disable showMenu when clicking, you can always change the settings on the gnome extensions page / gnome tweak
- Add a drop-down menu when you click the extension in the desktop top bar which gives you the setting option

BTW Great extension :)

ViB

**Comment by injcristianrojas** [comment]
I'm planning on doing option number 2 in the future, when GNOME Extensions documentation improves. Do you have an example of that?

**Comment by vicentebolea** [comment]
@injcristianrojas unfortunately I do not have experience with gnome/gtk. My realm is in Qt. 

I can see that this extension does have a button that brings you to settings: https://gitlab.com/jenslody/gnome-shell-extension-openweather

![Screenshot from 2021-04-02 17-20-11](https://user-images.githubusercontent.com/939798/113455081-bfcbfa80-93d7-11eb-836c-fc60305b4d71.png)

**Comment by injcristianrojas** [comment]
Check out the [class](https://github.com/injcristianrojas/UTCClock/tree/class) branch. Follow the manual install instructions and get back to me.

**Comment by vicentebolea** [comment]
@injcristianrojas I just tested it. I looks fantastic! Thats a big improvement. +1

BTW you might want to change feature branch names from from a single noun to a sentence which describes the feature such as:

`adding-dropdown-menu`

it would make navigating your branches easier.

**Comment by injcristianrojas** [comment]
I named it "class" because I did a complete rewrite of the extension, using class-based Javascript this time.

If you see any bugs, please submit a new issue. Thank you very much.
