### ISSUE TITLE
Doesn't show up on https://extensions.gnome.org/ for Ubuntu 21.10 beta

### ISSUE THREAD

**Issue by FastThenLeft** [injcristianrojas/UTCClock#16]
Just an FYI in case something needs to be changed. I'm running Ubuntu 21.10 Beta (release is Oct 14) and testing my normal apps of which UTCClock is one of them. When I go to https://extensions.gnome.org/, UTCClock does not show up as an extension if I have "Compatible with current version" picked. If I choose "All versions", then the installation button says, "INCOMPATIBLE".

The system is Wayland with Gnome 40.4.0.

**Comment by injcristianrojas** [comment]
Fixed. Should be up in a few minutes.

**Comment by FastThenLeft** [comment]
Thanks! I have UTCClock on all my computers (I'm a ham radio operator).

**Comment by injcristianrojas** [comment]
I've seen it's quite popular with ham radio ops. The new extension is now up.
