### ISSUE TITLE
Add option to view time in 12h format (AM/PM)

### ISSUE THREAD

**Issue by aadilayub** [injcristianrojas/UTCClock#18]
It'd be great to have this option, to make the system clock and UTC clock match. And also to ease cognitive load for people who don't use 24h time

![image](https://user-images.githubusercontent.com/31581044/168834616-85d5de4a-a5fb-4611-a984-268a20a5b9e0.png)

**Comment by injcristianrojas** [comment]
@aadilayub I've added a 12-hour functionality:
![image](https://user-images.githubusercontent.com/862690/170112210-c3e9aa52-0731-4e19-babe-e5977d5fa68e.png)
It's not syncronized with GNOME Shell's current 12/24 hour mode, so you can change it at will.
Try it using [manual install](https://github.com/injcristianrojas/UTCClock#manual), and let me know how it goes, so I can submit it to GNOME Extensions.

**Comment by alizehctl** [comment]
I tested it out. It works! Thanks :D

**Comment by injcristianrojas** [comment]
Thank you for your suggestion. I hope this helps more people that use the app.
