### ISSUE TITLE
Changing Timezone changes UTC time

### ISSUE THREAD

**Issue by jojo2357** [injcristianrojas/UTCClock#19]
Steps to reproduce:
Have extension enabled and visible in the top bar.
Change the timezone to a different UTC offset.
Observe Issue.

Expected behavior:
Traveling between time zones or otherwise changing the timezone should have no impact on the UTC clock.

Observed Behavior:
UTC clock shifts an hour in the opposite way the offset changed. (ie `UTC -7` -> `UTC-6` results in the clock shifting backwards an hour after shifting the system clock forward an hour. Shifting the system clock backwards results in a similar *forwards* shift in the UTC clock)

Notes:
Turning off and then on again the extension did not resolve the issue.

I did not restart my system to test further as I have outstanding work.

System info:
```
Pop!_OS 22.04 LTS
64 bit
GNOME 42.4
```

**Comment by jojo2357** [comment]
Also, if I set my time forward enough, the date and numeric day get tricked as well

**Comment by injcristianrojas** [comment]
PR tested, fixed and uploaded (version 32). Should be updated in a few hours. Thank you.

**Comment by jojo2357** [comment]
No, thank *you*. Were you able to replicate the issue as well as verify the fix?

**Comment by injcristianrojas** [comment]
Oh yeah... it was a great opportunity to try the GitHub CLI tool.
