### ISSUE TITLE
Is the clock meant to appear on the left or right?

### ISSUE THREAD

**Issue by lofidevops** [injcristianrojas/UTCClock#5]
I'm sure it used to appear on the right of the system clock, but now it's on the left. Is this correct?

**Notes:**

* I can't easily tell my extension version, but it is up-to-date as of 2019 May 22.
* I use https://extensions.gnome.org/extension/1060/timezone/ which also adds a widget next to the clock, but it's been running alongside UTCClock for months without issue. It is also up-to-date.

**Comment by injcristianrojas** [comment]
Sorry for the delay. It should appear to the right of the main clock.

**Comment by lofidevops** [comment]
It seems to be consistently on the right now. And now I know where it's meant to be! Thanks.
