### ISSUE TITLE
extension doesn't load under gnome 3.35.x

### ISSUE THREAD

**Issue by nirik** [injcristianrojas/UTCClock#6]
```
Jan 09 10:24:04 taim.scrye.com gnome-shell[2644]: JS ERROR: Extension utcclock@injcristianrojas.github.com: TypeError: Shell.util_format_date is not a function
                                                  update_time@/home/kevin/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/extension.js:46:23
                                                  enable@/home/kevin/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/extension.js:31:5
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:148:13
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:277:21
                                                  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:487:13
                                                  collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                                  _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:466:9
                                                  _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:496:13
                                                  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:527:13
                                                  init@resource:///org/gnome/shell/ui/extensionSystem.js:48:9
                                                  _initializeUI@resource:///org/gnome/shell/ui/main.js:242:5
                                                  start@resource:///org/gnome/shell/ui/main.js:138:5
                                                  @<main>:1:31
```

**Comment by injcristianrojas** [comment]
What OS are you using?

**Comment by nirik** [comment]
Fedora Rawhide.

**Comment by injcristianrojas** [comment]
Looks like an Gnome JS API issue. I'll look it over.

**Comment by rv4242** [comment]
I am using this on Ubuntu 19.10. It recently stopped working for me as well.
Gnome is currently 3.34

**Comment by rv4242** [comment]
I'm actually having issues with other extensions as well. Maybe it is a general problem. I'll find time to debug it this weekend.

**Comment by injcristianrojas** [comment]
I use Fedora 31, and I've been seeing a lot of gjs updates lately. I'll check it out.

**Comment by rv4242** [comment]
I finally got time to look into this, and in my case none of the extensions were working. I installed gnome-tweaks, re-enabled extensions, and they all worked.

**Comment by parasense** [comment]
Fedora 32, Gnome 3.36
Very similar issue to Nirik.

    Mar 31 21:51:34 caladan gnome-shell[10823]: JS ERROR: Extension utcclock@injcristianrojas.github.com: TypeError: Shell.util_format_date is not a function
                                                update_time@/home/parasense/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/extension.js:46:29
                                                enable@/home/parasense/.local/share/gnome-shell/extensions/utcclock@injcristianrojas.github.com/extension.js:31:5
                                                _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                                loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                                callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                                gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13

I feel like this began when Fedora was upgraded from 31 to 32 beta, or really when gnome was upgraded to 3.36.

**Comment by computorist** [comment]
Hacked on this a bit this morning. Loading under gnome-shell v3.36.1
```diff
 extension.js | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/extension.js b/extension.js
index f4e1407..534484b 100644
--- a/extension.js
+++ b/extension.js
@@ -17,6 +17,7 @@ function init() {
         can_focus: false,
         x_fill: true,
         y_fill: false,
+        y_align: St.Align.END,
         track_hover: true
     });
     label = new St.Label({
@@ -42,7 +43,7 @@ function update_time() {
     var now = new Date();
     now.setHours(now.getUTCHours());
     now.setMinutes(now.getUTCMinutes());
-    let time_format_string = seconds_displayed ? '%T' : '%H:%M';
-    let time_string = Shell.util_format_date(time_format_string, now);
-    label.set_text(time_string + ' UTC');
+    
+    var format = new Intl.DateTimeFormat('default', {hour: 'numeric', minute: 'numeric', hour12: false})
+    label.set_text(format.format(now) + " UTC");
 }
```

**Comment by domingusj** [comment]
Thanks @computorist, same tweak is working for me on Ubuntu 20.04.

**Comment by injcristianrojas** [comment]
@computorist could you create a PR for this?

**Comment by computorist** [comment]
Yes. I had meant to do that but was too busy at the time and then promptly forgot. I should be able to do that this afternoon.

**Comment by injcristianrojas** [comment]
@computorist don't worry. I just added it to baseline code. Will create a new version in a few minutes.

**Comment by injcristianrojas** [comment]
Commit 9e3446f3f980869fc251c5dcc70221ea2ec588b2 is ready, with @computorist's code. Awaiting review in Extensions website.

**Comment by injcristianrojas** [comment]
The new version with @computorist's modifications has been published. OK to close?

**Comment by nirik** [comment]
Yep. It's working here... thanks!

**Comment by injcristianrojas** [comment]
Having the original reporter's blessing, closing.
