### ISSUE TITLE
Setting for opacity

### ISSUE THREAD

**Issue by jhpratt** [injcristianrojas/UTCClock#7]
Having the ability for opacity to be 255 instead of 200 would be great. I've found myself having to go in and manually adjusting this every time an update is released.

**Comment by injcristianrojas** [comment]
I will add the option for opacity. I did this at 200 to not confuse the UTC clock with GNOME Shell's main clock.

**Comment by injcristianrojas** [comment]
New feature added in release v11. Submitted to Extensions.

**Comment by jhpratt** [comment]
Awesome, thanks!
