### ISSUE TITLE
Doesn't work with Gnome 3.38.1

### ISSUE THREAD

**Issue by FastThenLeft** [injcristianrojas/UTCClock#9]
Ubuntu 20.10 released with Gnome 3.38.1 and the extension no longer works. Too bad because it did EXACTLY what I wanted and was very valuable to me as a ham radio operator.

**Comment by injcristianrojas** [comment]
Just pushed a fix to GNOME Extensions (8e576eec952e912da92b893da41ce9457609ca96). The reviewers should check it and it should be available in a few hours.

**Comment by FastThenLeft** [comment]
Thanks for fixing it so quickly! It's so important to me that I was holding off upgrading my other machines until it ran under Ubuntu 20.10.

**Comment by injcristianrojas** [comment]
Try doing a manual install (see https://github.com/injcristianrojas/UTCClock#manual). The GNOME Extensions admins are taking their time to review the latest version of the app.

**Comment by FastThenLeft** [comment]
That's what I did and it works great! I've already closed the ticket.
Thanks for a great app. I use it every day since I'm a ham radio operator
(N9KT) and need to be constantly reminded of the time in UTC since I do a
lot of satellite work.
-David, N9KT

**Comment by injcristianrojas** [comment]
Great to know that it's useful to you. The GNOME Foundation says that they'll improve the API documentation. That will allow me to make it better.

**Comment by FastThenLeft** [comment]
FYI, the *new* release on the Gnome Extensions page (
https://extensions.gnome.org/extension/1183/utcclock/) is broken! Something
seems to have been left off.

Updating from your Git page works.

Using Ubuntu 20.10 & Gnome 3.38.1 the error is:

The settings of extension utcclock@injcristianrojas.github.com had an error:
```
Error: Schema org.gnome.shell.extensions.utcclock could not be found for
extension utcclock@injcristianrojas.github.com. Please check your
installation.
```

Stack trace:
```
getSettings@/home/david/.local/share/gnome-shell/extensions/
utcclock@injcristianrojas.github.com/convenience.js:88:15
_init@/home/david/.local/share/gnome-shell/extensions/
utcclock@injcristianrojas.github.com/prefs_window.js:20:38
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_init@/home/david/.local/share/gnome-shell/extensions/
utcclock@injcristianrojas.github.com/prefs.js:29:22
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
buildPrefsWidget@/home/david/.local/share/gnome-shell/extensions/
utcclock@injcristianrojas.github.com/prefs.js:36:17
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
